# Generated by Django 5.0.1 on 2024-03-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_movieDB',
            field=models.CharField(default='movie', max_length=10),
        ),
    ]
