# Generated by Django 5.0.1 on 2024-03-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0003_alter_post_type_moviedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_movieDB',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('TVSERIES', 'TvSeries'), ('SEASON', 'Season'), ('EPISODE', 'Episode'), ('PERSON', 'Person')], max_length=10),
        ),
    ]
