# Generated by Django 5.0.1 on 2024-03-26 00:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0005_alter_post_type_moviedb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_movieDB',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movieDB', models.CharField(max_length=20)),
                ('type_movieDB', models.CharField(choices=[('MOVIE', 'Filme'), ('TVSERIES', 'Série de TV'), ('SEASON', 'Temporada'), ('EPISODE', 'Episódio'), ('PERSON', 'Pessoa')], max_length=10)),
                ('image_movieDB', models.CharField(max_length=150)),
                ('text_review', models.TextField()),
                ('data_review', models.DateTimeField(default=datetime.datetime.now)),
                ('rate_review', models.IntegerField(default=1)),
                ('publicado', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
