# Generated by Django 5.0.1 on 2024-03-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0006_remove_post_image_moviedb_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
