# Generated by Django 5.0.1 on 2024-03-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
