# Generated by Django 5.0.1 on 2024-03-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0009_remove_post_id_post_id_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='id_post',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
